#!/bin/bash

echo -e "\e[1;30m\n====\nexpected output:\n========\n\e[0m \n"
echo $(cat tasks/03_task/log${1}/esp)
echo -e "\n\e[31m( error )\n"
echo $(cat tasks/03_task/log${1}/esp_error)
echo -e "\n\e[34m( exit code )\n"
echo $2
echo -e "\e[1;30m\n========\nyour output:\n========\n\e[0m"
echo $(cat tasks/03_task/log${1}/out)
echo -e "\n\e[31m( error )\n"
echo $(cat tasks/03_task/log${1}/out_error)
echo -e "\n\e[34m( exit code )\n"
echo $3
echo -e "\e[1;30m\n================\n\e[0m"
