#!/bin/bash
echo -e "=====\nTesting case $1"
command="                                          /bin/ls                                                                                                                                                                                                                                                                                  "

echo "$command" > tmp_file

echo -e "cheking input:\n${command}\n"

cat tmp_file | sh > "tasks/03_task/log${1}/esp" 2> "tasks/03_task/log${1}/esp_error"
excod1=$?
cat tmp_file | ./hsh > "tasks/03_task/log${1}/out" 2> "tasks/03_task/log${1}/out_error"
excod2=$?

if ! diff "tasks/03_task/log${1}/out" "tasks/03_task/log${1}/esp"
   then
    ./fail
    ./check_differences $1 $excod1 $excod2
else
    ./success
    ./check_differences $1 $excod1 $excod2
fi
