#!/bin/bash
echo -e "=====\nTesting case $1"
command="ls"

echo -e "cheking input:\n\e[47;30m"
echo -e "$command"
echo -en "\e[0m"


echo "$command" | sh > "tasks/03_task/log${1}/esp" 2> "tasks/03_task/log${1}/esp_error"
excod1=$?
echo "$command" | ./hsh > "tasks/03_task/log${1}/out" 2> "tasks/03_task/log${1}/out_error"
excod2=$?

if ! diff "tasks/03_task/log${1}/out" "tasks/03_task/log${1}/esp"
   then
    ./fail
    ./check_differences $1 $excod1 $excod2
else
    ./success
fi
